"""create signal tables

Revision ID: 005
Revises: 004_add_institutional_plan
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '005'
down_revision = '004_create_prediction_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Crear tabla user_signals
    op.create_table('user_signals',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('pair', sa.String(length=10), nullable=False),
        sa.Column('signal_type', mysql.ENUM('buy', 'sell', 'hold'), nullable=False),
        sa.Column('strength', mysql.ENUM('weak', 'medium', 'strong'), nullable=False),
        sa.Column('confidence', sa.DECIMAL(precision=5, scale=2), nullable=False),
        sa.Column('entry_price', sa.DECIMAL(precision=10, scale=5), nullable=False),
        sa.Column('stop_loss', sa.DECIMAL(precision=10, scale=5), nullable=True),
        sa.Column('take_profit', sa.DECIMAL(precision=10, scale=5), nullable=True),
        sa.Column('brain_type', sa.String(length=20), nullable=False),
        sa.Column('style', sa.String(length=20), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('expires_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('is_completed', sa.Boolean(), server_default='0', nullable=True),
        sa.Column('actual_price_at_expiry', sa.DECIMAL(precision=10, scale=5), nullable=True),
        sa.Column('signal_success', sa.Boolean(), nullable=True),
        sa.Column('success_percentage', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column('signal_quality', sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    # Crear tabla user_signal_limits
    op.create_table('user_signal_limits',
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('plan_type', sa.String(length=20), nullable=False),
        sa.Column('max_signals_per_day', sa.Integer(), nullable=False),
        sa.Column('signals_used_today', sa.Integer(), server_default='0', nullable=True),
        sa.Column('last_reset_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id')
    )
    
    # Crear índices
    op.create_index('idx_user_signals_user_id', 'user_signals', ['user_id'])
    op.create_index('idx_user_signals_created_at', 'user_signals', ['created_at'])
    op.create_index('idx_user_signals_pair', 'user_signals', ['pair'])
    op.create_index('idx_user_signals_brain_type', 'user_signals', ['brain_type'])
    op.create_index('idx_user_signals_style', 'user_signals', ['style'])
    op.create_index('idx_user_signals_is_completed', 'user_signals', ['is_completed'])
    op.create_index('idx_user_signals_user_created', 'user_signals', ['user_id', 'created_at'])
    op.create_index('idx_user_signals_completed', 'user_signals', ['is_completed', 'created_at'])
    
    op.create_index('idx_user_signal_limits_plan_type', 'user_signal_limits', ['plan_type'])
    op.create_index('idx_user_signal_limits_last_reset_date', 'user_signal_limits', ['last_reset_date'])
    op.create_index('idx_user_signal_limits_reset', 'user_signal_limits', ['last_reset_date', 'user_id'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar índices
    op.drop_index('idx_user_signal_limits_reset', table_name='user_signal_limits')
    op.drop_index('idx_user_signal_limits_last_reset_date', table_name='user_signal_limits')
    op.drop_index('idx_user_signal_limits_plan_type', table_name='user_signal_limits')
    
    op.drop_index('idx_user_signals_completed', table_name='user_signals')
    op.drop_index('idx_user_signals_user_created', table_name='user_signals')
    op.drop_index('idx_user_signals_is_completed', table_name='user_signals')
    op.drop_index('idx_user_signals_style', table_name='user_signals')
    op.drop_index('idx_user_signals_brain_type', table_name='user_signals')
    op.drop_index('idx_user_signals_pair', table_name='user_signals')
    op.drop_index('idx_user_signals_created_at', table_name='user_signals')
    op.drop_index('idx_user_signals_user_id', table_name='user_signals')
    
    # Eliminar tablas
    op.drop_table('user_signal_limits')
    op.drop_table('user_signals')
    
    # ### end Alembic commands ### 