"""insert signal limits for existing users

Revision ID: 006
Revises: 005
Create Date: 2024-01-15 10:01:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Insertar límites por defecto para usuarios existentes
    # Obtener todos los usuarios que no tienen límites de señales
    connection = op.get_bind()
    
    # Insertar límites para usuarios existentes (plan starter por defecto)
    connection.execute(sa.text("""
        INSERT INTO user_signal_limits (user_id, plan_type, max_signals_per_day)
        SELECT id, 'starter', 5 FROM users 
        WHERE id NOT IN (SELECT user_id FROM user_signal_limits)
    """))
    
    # Insertar límites específicos para diferentes planes (si existen)
    # Estos se pueden ajustar según los usuarios existentes
    connection.execute(sa.text("""
        INSERT INTO user_signal_limits (user_id, plan_type, max_signals_per_day) VALUES 
        (1, 'starter', 5),
        (2, 'trader', 20),
        (3, 'expert', 50),
        (4, 'premium', 100),
        (5, 'institutional', -1)
        ON DUPLICATE KEY UPDATE 
            plan_type = VALUES(plan_type),
            max_signals_per_day = VALUES(max_signals_per_day)
    """))
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Eliminar todos los límites de señales
    connection = op.get_bind()
    connection.execute(sa.text("DELETE FROM user_signal_limits"))
    
    # ### end Alembic commands ### 